Deneme/Models/Customer.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Deneme.Models
{
    public partial class Customer
    {
    
        [Key]
        public string CustomerId { get; set; } = null!;
        
        public string CompanyName { get; set; } = null!;
        public string? ContactName { get; set; }
        public string? ContactTitle { get; set; }
        public string? Address { get; set; }
        public string? City { get; set; }
        public string? Region { get; set; }
        public string? PostalCode { get; set; }
        public string? Country { get; set; }
        public string? Phone { get; set; }
        public string? Fax { get; set; }
    }
}

Deneme/Controllers/CustomerController.cs
using Deneme.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Deneme.Controllers
{
    public class CustomerController : Controller
    {
        private readonly AppDbContext _context;
        private readonly CustomerRepository _customerRepository;

        Customer customer = new Customer();
        

        public CustomerController(AppDbContext context)
        {
            _context = context;
            _customerRepository = new CustomerRepository();
        }
        [HttpGet]
        public IActionResult Customer()
        {
            var customers = _context.Customers.ToList();
            return View(customers);
        }
        [HttpPost]
        public IActionResult CustomerDetails()
        {
            var customers = _context.Customers.ToList();

            return View(customers);
        }

        [HttpPost]
    
        public IActionResult AddCustomer(Customer Customer)
        { 
            return View(customer);
        }

        [HttpPost]
        public IActionResult Save(Customer customer)
        {
            Customer newCustomer = new Customer()
            { CompanyName = customer.CompanyName, Address = customer.Address, City = customer.City, ContactName = customer.ContactName, ContactTitle = customer.ContactTitle, Country = customer.Country, CustomerId = customer.CustomerId, Fax = customer.Fax, Phone = customer.Phone, PostalCode = customer.PostalCode, Region = customer.Region };
            _context.Add(customer);
            _context.SaveChanges();
              

            return View();
        }
    }
}

Deneme/Views/Customer/AddCustomer.cshtml
@model Customer
<form asp-controller="Customer" asp-action="AddCustomer" method="post">
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" asp-for="CustomerId" name="CustomerId" class="form-control" required  placeholder="Id veriniz">
    </div>
<div class="mb-3">
    <label  class="form-label">Company Name</label>
        <input type="text" asp-for="CompanyName" class="form-control" name="CompanyName" placeholder="Şirket ismi giriniz">
</div>

<div class="mb-3">
    <label  class="form-label">ContactName</label>
        <input type="text" asp-for="ContactName" class="form-control" name="ContactName" placeholder="Yetkili kişi giriniz">
</div>

<div class="mb-3">
    <label  class="form-label">ContactTitle</label>
        <input type="text" asp-for="ContactTitle" class="form-control" name="ContactTitle" placeholder="iletişim giriniz">
</div>

<div class="mb-3">
    <label  class="form-label">Address</label>
        <input type="text" asp-for="Address" class="form-control" name="Address" placeholder="adres giriniz">
</div>
<div class="mb-3">
    <label  class="form-label">City</label>
        <input type="text" asp-for="City" class="form-control" name="City" placeholder="şehir giriniz">
</div>
<div class="mb-3">
    <label  class="form-label">region</label>
        <input type="text" asp-for="Region" class="form-control" name="Region" placeholder="bölge giriniz">
</div>
<div class="mb-3">
    <label  class="form-label">postalcode</label>
        <input type="text" asp-for="PostalCode" class="form-control" name="PostalCode" placeholder="posta kodu giriniz">
</div>
<div class="mb-3">
    <label  class="form-label">country</label>
        <input type="text" asp-for="Country" class="form-control" name="Country" placeholder="ülke giriniz">
</div>
<div class="mb-3">
    <label  class="form-label">phone</label>
        <input type="text" asp-for="Phone" class="form-control" name="Phone" placeholder="telefon numarası giriniz">
</div>
<div class="mb-3">
    <label  class="form-label">fax</label>
        <input type="text" asp-for="Fax" class="form-control" name="Fax" placeholder="fax numarası giriniz">
</div>
    
    <button type="submit" class="form-control btn btn-primary" asp-controller="Customer" asp-action="Save" method="post">müşteri ekle</button>
    <hr />


</form>

Deneme/Views/Customer/Customer.cshtml
@model List<Customer>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form action="/Customer/CustomerDetails" class="form" method="post">
    <table class="table">
  
    <button type="submit" class="form-control btn btn-primary" asp-controller="Customer" asp-action="CustomerDetails" method="post">Detay sayfasına git</button>
    <hr />   
    <button type="submit" class="form-control btn btn-primary" asp-controller="Customer" asp-action="AddCustomer" method="post">müşteri ekleme sayfasına git</button>



        <thead>
            <tr>
                <th>id</th>
                <th>isim</th>
                <th>şehir</th>
                <th>ülke</th>
                <th>şirket ismi</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
       <tr>
           <td>@item.CustomerId</td>
           <td>@item.ContactName</td>
           <td>@item.City</td>
           <td>@item.Country</td>
           <td>@item.CompanyName</td>
       </tr> 
         }
    </tbody>
    </table>
    </form>

Deneme/Views/Customer/CustomerDetails.cshtml
@model List<Customer>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<label>
    Burası detay sayfasıdır.
</label>
    <table class="table-details">

        <thead>
        <tr>
            <td>ID</td>
            <td>CompanyName</td>
            <td>ContactName</td>
            <td>ContactTitle</td>
            <td>Address</td>
            <td>City</td>
            <td>Region</td>
            <td>PostalCode</td>
            <td>Country</td>
            <td>Phone</td>
            <td>Fax</td>
        </tr>
        </thead>
        <hr />
        <tbody>
            @foreach (var item in Model)
        {
            <tr>
                <td>@item.CustomerId</td>
                <td>@item.ContactName</td>
                <td>@item.ContactName</td>           
                    <td>@item.Address</td>
                    <td>@item.City</td>
                    <td>@item.Region</td>
                    <td>@item.PostalCode</td>
                    <td>@item.Country</td>
                    <td>@item.Phone</td>
                    <td>@item.Fax</td>
            </tr>
        }
        </tbody>
    </table>

Deneme/Views/Customer/Save.cshtml
@{
    ViewData["Title"] = "Save";
}

<h1>Save</h1>